remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Recipe Ratings Analysis
description: DSC 80 Final Project
<iframe
  src="ratings_histogram.html"
  width="800"
  height="600"
  frameborder="0"
></iframe>
